### ISSUE TITLE
Sonarqube integration

### ISSUE THREAD

**Issue by Karma-Tsering** [OpenPecha/monlamai-app-web#198]
### Description
SonarQube is an on-premise analysis tool designed to detect coding issues in [30+ languages, frameworks, and IaC platforms](https://rules.sonarsource.com/). By integrating directly with your [CI pipeline](https://docs.sonarsource.com/sonarqube/latest/analyzing-source-code/ci-integration/overview/) or on one of our supported DevOps platforms, your code is checked against an extensive set of rules that cover many attributes of code, such as maintainability, reliability, and security issues on each merge/pull request. We going to integrate Sonarqube with our project.

### Implementation plan
Setting up the sonarqube
Integrate it with github

### updated task
Test coverage is not reflecting in sonarcloud report. To achieve this, need  to run the test from github action and then sonarscan should get the coverage report
- [x] Test coverage should reflect in sonarcloud

**Comment by ta4tsering** [comment]
Since @kaldan007 created the Sonarcloud account, waiting for the admin credentials from him.
